services:
  - type: web
    name: kitchensync-api
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node src/app.js
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000 