services:
  - type: web
    name: kitchensync-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node src/app.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000 